/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author brand
 */
public class FramePrincipal extends javax.swing.JFrame {

    int x, y;

    public FramePrincipal() {
        this.setUndecorated(true);
        initComponents();

        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        
        //PnlNuevaAreaTrabajo bbtn = new PnlNuevaAreaTrabajo();
        //PnlAreaTrabajo bbtn = new PnlAreaTrabajo();
        //PnlTablaDatos bbtn = new PnlTablaDatos();
        //PnlRegistroPersona bbtn = new PnlRegistroPersona();
        /*bbtn.setSize(900, 77);
        bbtn.setLocation(0, 1);
        panelContenedor.removeAll();
        panelContenedor.add(bbtn, BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        LblPrivilegio = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        PanelMinCerrar = new javax.swing.JPanel();
        PanelFechaHora = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(38, 50, 56));
        panelFondo.setPreferredSize(new java.awt.Dimension(900, 775));
        panelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelFondoMouseDragged(evt);
            }
        });
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });

        LblPrivilegio.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LblPrivilegio.setForeground(new java.awt.Color(255, 255, 255));
        LblPrivilegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ControlAccesoAdmin.png"))); // NOI18N
        LblPrivilegio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panelBarra.setBackground(new java.awt.Color(38, 50, 56));
        panelBarra.setLayout(new java.awt.BorderLayout());

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogOut2.png"))); // NOI18N
        btnLogout.setToolTipText("Cerrar Sesión");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogOut3.png"))); // NOI18N
        btnLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogOut1.png"))); // NOI18N

        panelContenedor.setBackground(new java.awt.Color(38, 50, 56));
        panelContenedor.setLayout(new java.awt.BorderLayout());

        PanelMinCerrar.setBackground(new java.awt.Color(38, 50, 56));
        PanelMinCerrar.setLayout(new java.awt.BorderLayout());

        PanelFechaHora.setBackground(new java.awt.Color(38, 50, 56));
        PanelFechaHora.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(LblPrivilegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMinCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout)))
            .addComponent(PanelFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblPrivilegio))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(PanelMinCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)))
                .addGap(18, 18, 18)
                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(PanelFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);

    }//GEN-LAST:event_panelFondoMouseDragged

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelFondoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LblPrivilegio;
    public javax.swing.JPanel PanelFechaHora;
    public javax.swing.JPanel PanelMinCerrar;
    public javax.swing.JButton btnLogout;
    public javax.swing.JPanel panelBarra;
    public javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
