/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jaasiel Guerra
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InisioSesion
     */
    
    CambiarPanel cambiar;
    boolean pulso = true;
    public InicioSesion() {
        initComponents();
        
        
        /*Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = (dim.width/8)*2;
        int y = (dim.height/8)*5;
        
        System.out.println("Tamanio Login: "+x+ "," + y);*/
        
        this.setSize(340,480);
        this.setLocationRelativeTo(null);
        
        
        cambiar = new CambiarPanel(this.Contenedor, new PnlHuella());//cambiar panel
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();
        PnlInferior = new javax.swing.JPanel();
        btnAccesoAlter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        Encabezado.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control de Acceso");
        Encabezado.add(jLabel1, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(Encabezado, java.awt.BorderLayout.PAGE_START);

        Contenedor.setLayout(new java.awt.BorderLayout());
        PanelPrincipal.add(Contenedor, java.awt.BorderLayout.CENTER);

        btnAccesoAlter.setText("Acceso Alternativo");
        btnAccesoAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoAlterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlInferiorLayout = new javax.swing.GroupLayout(PnlInferior);
        PnlInferior.setLayout(PnlInferiorLayout);
        PnlInferiorLayout.setHorizontalGroup(
            PnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInferiorLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btnAccesoAlter)
                .addContainerGap())
        );
        PnlInferiorLayout.setVerticalGroup(
            PnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlInferiorLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(btnAccesoAlter)
                .addContainerGap())
        );

        PanelPrincipal.add(PnlInferior, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoAlterActionPerformed
        //boton acceso alternativo
        
        if(pulso){
            cambiar = new CambiarPanel(this.Contenedor, new PnlCredenciales());
            this.btnAccesoAlter.setText("<= Regresar");
            pulso = false;
        }else{
            cambiar = new CambiarPanel(this.Contenedor, new PnlHuella());
            this.btnAccesoAlter.setText("Acceso Alternativo");
            pulso = true;
        }
        
    }//GEN-LAST:event_btnAccesoAlterActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PnlInferior;
    private javax.swing.JButton btnAccesoAlter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
