/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.TablaRenderColor;
import Vista.TextPrompt;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author brand
 */
public class PnlAreaTrabajo extends javax.swing.JPanel {

   
    private TextPrompt buscar;
    
    public PnlAreaTrabajo() {
        initComponents();
        
       // TEXT PROMPT
        TextPrompt nombre = new TextPrompt("Buscar", TxtBuscar);
        nombre.setForeground(new Color(117,117,117 ,1));
        nombre.changeAlpha(0.8f);
        nombre.changeStyle(Font.ITALIC);
        
        // COLOR TABLA
       
        
        TablaRenderColor tabla = new TablaRenderColor();
        tabla.setCellRender(Datos);

        Datos.getTableHeader().setAlignmentX(CENTER_ALIGNMENT);
        Datos.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        Datos.getTableHeader().setOpaque(false);
        Datos.getTableHeader().setBackground(new Color(0, 69, 165));
        Datos.getTableHeader().setForeground(new Color(255, 255, 255));
        Datos.setRowHeight(25);
        ((DefaultTableCellRenderer) Datos.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);
        
        
        // SCROLLPANE
        jScrollPane.setBackground(new Color(0, 69, 165));
        jScrollPane.getViewport().getView().setBackground(new Color(0, 69, 165));
        jScrollPane.getViewport().getView().setForeground(new Color(0, 69, 165));

    }

/**
     * Creates new form PnlTablaDatos
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JTextField();
        TxtBusquedaPor = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BtnNuevo = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        Datos = new javax.swing.JTable();

        setBackground(new java.awt.Color(38, 50, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(38, 50, 56));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(97, 203, 255))); // NOI18N

        TxtBuscar.setBackground(new java.awt.Color(222, 222, 222));
        TxtBuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtBuscar.setBorder(null);

        TxtBusquedaPor.setBackground(new java.awt.Color(222, 222, 222));
        TxtBusquedaPor.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtBusquedaPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUSCAR POR", "DPI", "NOMBRE" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnBuscar2.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusable(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnBuscar3.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnBuscar1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TxtBusquedaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBusquedaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(38, 50, 56));
        jPanel3.setPreferredSize(new java.awt.Dimension(141, 55));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnNuevo2.png"))); // NOI18N
        BtnNuevo.setToolTipText("");
        BtnNuevo.setBorder(null);
        BtnNuevo.setBorderPainted(false);
        BtnNuevo.setContentAreaFilled(false);
        BtnNuevo.setFocusable(false);
        BtnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnNuevo3.png"))); // NOI18N
        BtnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnNuevo1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 5, 0);
        jPanel3.add(BtnNuevo, gridBagConstraints);

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEditar2.png"))); // NOI18N
        BtnEditar.setBorder(null);
        BtnEditar.setBorderPainted(false);
        BtnEditar.setContentAreaFilled(false);
        BtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEditar.setFocusable(false);
        BtnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEditar3.png"))); // NOI18N
        BtnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEditar1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 5, 0);
        jPanel3.add(BtnEditar, gridBagConstraints);

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEliminar2.png"))); // NOI18N
        BtnEliminar.setBorder(null);
        BtnEliminar.setBorderPainted(false);
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setFocusable(false);
        BtnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEliminar3.png"))); // NOI18N
        BtnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnEliminar1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 5, 63);
        jPanel3.add(BtnEliminar, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(38, 50, 56));

        Datos.setBackground(new java.awt.Color(51, 255, 0));
        Datos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Area de trabajo", "Entrada", "Salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Datos.setGridColor(new java.awt.Color(0, 0, 0));
        Datos.setSelectionBackground(new java.awt.Color(97, 203, 255));
        jScrollPane.setViewportView(Datos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnEditar;
    public javax.swing.JButton BtnEliminar;
    public javax.swing.JButton BtnNuevo;
    public javax.swing.JTable Datos;
    public javax.swing.JTextField TxtBuscar;
    public javax.swing.JComboBox<String> TxtBusquedaPor;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
