/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author brand
 */
public class PnlBarraBotones extends javax.swing.JPanel {

    /**
     * Creates new form BarraBotones
     */
    public PnlBarraBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraBotones = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnAreaTrabajo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnHistorial = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        panelBarraBotones.setBackground(new java.awt.Color(33, 33, 33));
        panelBarraBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAdmin.setBackground(new java.awt.Color(51, 51, 51));
        btnAdmin.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Admin2.png"))); // NOI18N
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setFocusable(false);
        btnAdmin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Admin3.png"))); // NOI18N
        btnAdmin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Admin1.png"))); // NOI18N

        btnEmpleado.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleado.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Empleados2.png"))); // NOI18N
        btnEmpleado.setBorder(null);
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setContentAreaFilled(false);
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.setFocusable(false);
        btnEmpleado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Empleados3.png"))); // NOI18N
        btnEmpleado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Empleados1.png"))); // NOI18N

        btnAreaTrabajo.setBackground(new java.awt.Color(51, 51, 51));
        btnAreaTrabajo.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnAreaTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnAreaTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AreaTrabajo2.png"))); // NOI18N
        btnAreaTrabajo.setBorder(null);
        btnAreaTrabajo.setBorderPainted(false);
        btnAreaTrabajo.setContentAreaFilled(false);
        btnAreaTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAreaTrabajo.setFocusable(false);
        btnAreaTrabajo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AreaTrabajo3.png"))); // NOI18N
        btnAreaTrabajo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AreaTrabajo1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        btnHistorial.setBackground(new java.awt.Color(51, 51, 51));
        btnHistorial.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Historial2.png"))); // NOI18N
        btnHistorial.setToolTipText("Historial");
        btnHistorial.setBorder(null);
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorial.setFocusable(false);
        btnHistorial.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Historial3.png"))); // NOI18N
        btnHistorial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Historial1.png"))); // NOI18N

        btnImprimir.setBackground(new java.awt.Color(51, 51, 51));
        btnImprimir.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imprimir2.png"))); // NOI18N
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setBorder(null);
        btnImprimir.setBorderPainted(false);
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.setFocusable(false);
        btnImprimir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imprimir3.png"))); // NOI18N
        btnImprimir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imprimir1.png"))); // NOI18N

        btnAddUser.setBackground(new java.awt.Color(51, 51, 51));
        btnAddUser.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AddUsuario2.png"))); // NOI18N
        btnAddUser.setToolTipText("Agregar Empleado");
        btnAddUser.setBorder(null);
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.setFocusable(false);
        btnAddUser.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AddUsuario2.png"))); // NOI18N
        btnAddUser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AddUsuario1.png"))); // NOI18N

        javax.swing.GroupLayout panelBarraBotonesLayout = new javax.swing.GroupLayout(panelBarraBotones);
        panelBarraBotones.setLayout(panelBarraBotonesLayout);
        panelBarraBotonesLayout.setHorizontalGroup(
            panelBarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraBotonesLayout.createSequentialGroup()
                .addComponent(btnEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAreaTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin)
                .addGroup(panelBarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarraBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnHistorial)
                        .addGap(46, 46, 46)
                        .addComponent(btnImprimir)
                        .addGap(46, 46, 46)
                        .addComponent(btnAddUser)
                        .addGap(35, 35, 35))))
        );
        panelBarraBotonesLayout.setVerticalGroup(
            panelBarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraBotonesLayout.createSequentialGroup()
                .addGroup(panelBarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAreaTrabajo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBarraBotonesLayout.createSequentialGroup()
                        .addGroup(panelBarraBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHistorial)
                            .addComponent(btnImprimir)
                            .addComponent(btnAddUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddUser;
    public javax.swing.JButton btnAdmin;
    public javax.swing.JButton btnAreaTrabajo;
    public javax.swing.JButton btnEmpleado;
    public javax.swing.JButton btnHistorial;
    public javax.swing.JButton btnImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBarraBotones;
    // End of variables declaration//GEN-END:variables
}
