/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.TextPrompt;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author brand
 */
public class PnlRegistroPersona extends javax.swing.JPanel {

    
    /**
     * Creates new form PnlTablaDatos
     */
    public PnlRegistroPersona() {
        initComponents();
        
        TextPrompt nombre = new TextPrompt("Nombre", TxtNombre);
        nombre.setForeground(new Color(117,117,117 ,1));
        nombre.changeAlpha(0.8f);
        nombre.changeStyle(Font.ITALIC);
        
        TextPrompt apellido = new TextPrompt("Apellido", TxtApellido);
        apellido.setForeground(new Color(117,117,117 ,1));
        apellido.changeAlpha(0.8f);
        apellido.changeStyle(Font.ITALIC);
        
        TextPrompt dpi = new TextPrompt("DPI", IntDPI);
        dpi.setForeground(new Color(117,117,117 ,1));
        dpi.changeAlpha(0.8f);
        dpi.changeStyle(Font.ITALIC);
        
        TextPrompt user = new TextPrompt("Usuario", TxtUsuario);
        user.setForeground(new Color(117,117,117 ,1));
        user.changeAlpha(0.8f);
        user.changeStyle(Font.ITALIC);
        
        TextPrompt pass = new TextPrompt("Contraseña", TxtPassword);
        pass.setForeground(new Color(117,117,117 ,1));
        pass.changeAlpha(0.8f);
        pass.changeStyle(Font.ITALIC);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BtnFoto = new javax.swing.JButton();
        BtnHuella = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JPasswordField();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        IntDPI = new javax.swing.JTextField();
        CombAreasT = new javax.swing.JComboBox<>();
        LblAdmin = new javax.swing.JLabel();
        CheckAdmin = new javax.swing.JCheckBox();
        BtnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(38, 50, 56));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(38, 50, 56));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRAR EMPLEADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(97, 203, 255))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(38, 50, 56));
        jPanel1.setPreferredSize(new java.awt.Dimension(478, 135));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        BtnFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnTomarFoto2.png"))); // NOI18N
        BtnFoto.setBorder(null);
        BtnFoto.setBorderPainted(false);
        BtnFoto.setContentAreaFilled(false);
        BtnFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnFoto.setFocusable(false);
        BtnFoto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnFoto.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnFoto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnTomarFoto3.png"))); // NOI18N
        BtnFoto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnTomarFoto1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 11, 0);
        jPanel1.add(BtnFoto, gridBagConstraints);

        BtnHuella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnCapturarHuella2.png"))); // NOI18N
        BtnHuella.setBorder(null);
        BtnHuella.setBorderPainted(false);
        BtnHuella.setContentAreaFilled(false);
        BtnHuella.setFocusable(false);
        BtnHuella.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnHuella.setMaximumSize(new java.awt.Dimension(50, 23));
        BtnHuella.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnHuella.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnCapturarHuella3.png"))); // NOI18N
        BtnHuella.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnCapturarHuella1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 11, 0);
        jPanel1.add(BtnHuella, gridBagConstraints);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(38, 50, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtUsuario.setBackground(new java.awt.Color(222, 222, 222));
        TxtUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtUsuario.setBorder(null);
        TxtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuario.setName(""); // NOI18N
        jPanel3.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 450, 30));

        TxtPassword.setBackground(new java.awt.Color(222, 222, 222));
        TxtPassword.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtPassword.setBorder(null);
        jPanel3.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 43, 450, 30));

        TxtNombre.setBackground(new java.awt.Color(222, 222, 222));
        TxtNombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtNombre.setBorder(null);
        jPanel3.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 86, 450, 30));

        TxtApellido.setBackground(new java.awt.Color(222, 222, 222));
        TxtApellido.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TxtApellido.setBorder(null);
        jPanel3.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 127, 450, 30));

        IntDPI.setBackground(new java.awt.Color(222, 222, 222));
        IntDPI.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        IntDPI.setBorder(null);
        jPanel3.add(IntDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 450, 30));

        CombAreasT.setBackground(new java.awt.Color(222, 222, 222));
        CombAreasT.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        CombAreasT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AREA DE TRABAJO" }));
        CombAreasT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(CombAreasT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 211, 450, 30));

        LblAdmin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        LblAdmin.setText("¿Es Administrador?");
        jPanel3.add(LblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 157, 38));

        CheckAdmin.setBackground(new java.awt.Color(38, 50, 56));
        CheckAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(CheckAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnGuardar2.png"))); // NOI18N
        BtnGuardar.setToolTipText("Guardar");
        BtnGuardar.setBorder(null);
        BtnGuardar.setBorderPainted(false);
        BtnGuardar.setContentAreaFilled(false);
        BtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGuardar.setFocusable(false);
        BtnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnGuardar3.png"))); // NOI18N
        BtnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BtnGuardar1.png"))); // NOI18N
        jPanel3.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnFoto;
    public javax.swing.JButton BtnGuardar;
    public javax.swing.JButton BtnHuella;
    public javax.swing.JCheckBox CheckAdmin;
    public javax.swing.JComboBox<String> CombAreasT;
    public javax.swing.JTextField IntDPI;
    public javax.swing.JLabel LblAdmin;
    public javax.swing.JTextField TxtApellido;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JPasswordField TxtPassword;
    public javax.swing.JTextField TxtUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
